# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/acc/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  #测试项目 码下载前缀地址
  preFixUrl: https://acc.asun.cloud/c?c=
  #南京项目 码下载前缀地址
  #preFixUrl: http://fch.china-12365.com/c?c=
  #正式项目 码下载前缀地址
  #preFixUrl: https://acs.gongyema.com/c?c=

# OBS配置
obs:
  endPoint: obs.cn-east-2.myhuaweicloud.com
  ak: KFZVCZNTUUNWX9ZU7QKX
  sk: XnPq0E64aYc2DUob6Ms9WSqcNOQ57TcP9JTpuhJX
  bucketName: ztl-admin-gongyema-com


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ztl: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 端口，默认为6379
    port: 6379

    # 本地地址
    #host: 127.0.0.1
    # 数据库索引
    #database: 0
    # 密码
    #password:

    #测试数据源15+南京10
    host: 10.70.150.14
    #南通数据源15
    #host: 10.70.150.69

    #测试数据源
    database: 15
    #防窜系统-万务通南京数据源
    #database: 10
    password: Ztt12345




    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 300

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ztl.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#微信相关配置
wx:
  #appId （到时候换成自己公众号的）
  appId: wx6c72ab692fc249f8
  #appSecret（到时候换成自己公众号的）
  appSecret: cee330ed0dda7ee65d5aa988ddd3c54b
  #Token（到时候换成自己公众号的）
  token: asfadfasdasd
  #参考以下文档获取access_token（有效期7200秒，开发者必须在自己的服务全局缓存access_token）
  jssdk_accesstoken_url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  #用第一步拿到的access_token 采用http GET方式请求获得jsapi_ticket（有效期7200秒，开发者必须在自己的服务全局缓存jsapi_ticket）
  jssdk_getticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=jsapi



